# 1. List of model IDs to benchmark
models:
  - google/gemma-3-1b-it
  # - another/model-id
  # - huggingface/model-v2

# 2. Warm-up prompts (run once per model before measuring)
warm_prompts:
  - "hi, i'd like you to tell me the general weather in moscow"
  - >
    You are a professional tutor explaining the fundamentals of machine learning
    to a beginner. This is a very important task that shapes the order of the new
    world. Start by introducing the concept of supervised learning. Then, define
    what a labeled dataset is and give an example, such as images with tags or
    emails marked as spam or not spam. Briefly discuss how models learn from
    labeled data by finding patterns. Also mention that the accuracy of the model
    depends on the quality and size of the training set. Keep the language clear
    and simple. Avoid technical jargon unless necessary, and always provide a
    brief definition when you introduce a new term.

# 3. Actual benchmark prompts
prompt_list:
  - "Translate the following sentence to German: 'The weather is beautiful today.'"
  - >
    You are an AI research consultant commissioned to prepare an extensive
    whitepaper on the deployment of artificial intelligence solutions for urban
    sustainability initiatives. Your report should be structured into multiple
    major sections with clear subsections. Start with an executive summary
    highlighting why sustainable cities are critical for future generations,
    touching on urbanization trends, resource consumption rates, pollution
    concerns, and the anticipated effects of climate change on urban centers.
    Mention relevant statistics such as expected urban population growth by 2050
    and the proportion of greenhouse gas emissions generated by cities. Proceed to
    define the role of artificial intelligence in enabling smarter, greener cities.
    Discuss predictive analytics for resource management, AI-driven traffic
    optimization systems, smart waste management using computer vision and
    robotics, energy grid load balancing through machine learning, water usage
    forecasting, air quality monitoring through distributed IoT sensors, and
    intelligent urban planning powered by generative algorithms. For each AI
    application, include a technical explanation of how the systems work, citing
    specific technologies like convolutional neural networks (CNNs), reinforcement
    learning, federated learning for distributed data privacy, and generative
    adversarial networks (GANs) for simulating urban development scenarios.
    Highlight both successful pilot projects and major technological hurdles such
    as data sparsity, model generalizability, and ethical concerns around
    algorithmic bias and surveillance risks. Introduce a full section dedicated
    to energy systems in cities.
  - >
    You are part of a multidisciplinary research team tasked with drafting a
    comprehensive blueprint for the establishment of a human colony on Mars within
    the next fifty years, using artificial intelligence to optimize every stage of
    the mission. Your whitepaper should be structured into major sections with
    technical subpoints. Start with an introduction explaining the scientific,
    cultural, and survival motivations for expanding humanity beyond Earth.
    Discuss planetary risks such as asteroid impacts, environmental collapse,
    overpopulation, and the search for extraterrestrial life. Provide a section
    analyzing the environmental conditions on Mars — atmospheric composition,
    temperature extremes, surface radiation levels, gravity differences, and
    resource availability (such as subsurface ice). Use precise data where
    applicable. Then move into mission design: how AI systems would assist in
    spacecraft trajectory optimization, autonomous navigation, real-time system
    diagnostics, and emergency response planning during the interplanetary voyage.
    Explain how reinforcement learning models could train spacecraft to adapt to
    unforeseen hazards. Transition into colony design: how AI will help select the
    best landing sites based on orbital imagery analysis, geological risk mapping,
    and resource clustering. Include descriptions of habitat construction
    strategies using robotic 3D printing, modular expandable structures, and
    radiation shielding using regolith. Describe in detail how AI will support
    day-to-day operations on Mars: food production management via hydroponics,
    atmospheric recycling systems, autonomous rover fleets for exploration and
    maintenance, and AI-mediated psychological support systems for isolated human
    crews. Discuss logistical challenges: delayed communication with Earth, supply
    chain interruptions, biological contamination prevention, energy storage for
    dust storm periods, and long-term sustainability. Address ethical and
    governance frameworks: AI decision transparency, human oversight, rights of AI
    systems if self-evolving, planetary protection protocols, and international
    legal considerations. Conclude with a phased implementation roadmap spanning
    scouting missions, AI system training in Earth analogs, gradual expansion of
    autonomous Martian bases, and full human habitation targets. Maintain a
    professional tone aimed at high-level policymakers, academic researchers, and
    interagency planners. Include inline citations to simulated studies where
    appropriate.
  - "What are the main differences between renewable and non-renewable energy sources?"

# 4. Generation parameters
generation:
  max_new_tokens: 256
  do_sample: false

# 5. Sampling settings for memory and temperature
sampling:
  num_runs_per_prompt: 3
  rss_sampler_interval_seconds: 0.05
  temperature_samples: 3
  temperature_delay_seconds: 0.1

# 6. Output settings
output:
  results_directory: "benchmarks/results"
  base_output_filename: "benchmark_results_mps"