# LLM Benchmark Configuration

model\_list:

* Qwen/Qwen2.5-1.5B-Instruct
* google/gemma-3-1b-it
* meta-llama/Llama-3.2-1B-Instruct

warm\_prompts:

* "Hello, how are you today?"
* "What is the capital of France?"
* "Write a short poem about clouds."

prompt\_list:

* "Translate the following sentence to German: 'The weather is beautiful today.'"
* "Explain the concept of quantum entanglement in simple terms."
* "Write a python function that calculates the factorial of a number."
* "Summarize the main plot points of the movie 'Inception'."
* "What are the main differences between renewable and non-renewable energy sources?"

num\_timed\_runs\_per\_prompt: 3

generation\_config:
max\_new\_tokens: 256
do\_sample: false

batch\_size: 1

# Advanced/optional settings
benchmark\_dtype: float16        # torch dtype for model weights